/* automatically generated by rust-bindgen 0.57.0 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Viewer {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ViewUnit {
    pub viewer: *mut Viewer,
}
#[test]
fn bindgen_test_layout_ViewUnit() {
    assert_eq!(
        ::std::mem::size_of::<ViewUnit>(),
        8usize,
        concat!("Size of: ", stringify!(ViewUnit))
    );
    assert_eq!(
        ::std::mem::align_of::<ViewUnit>(),
        8usize,
        concat!("Alignment of ", stringify!(ViewUnit))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<ViewUnit>())).viewer as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(ViewUnit),
            "::",
            stringify!(viewer)
        )
    );
}
pub type ViewUnit_t = ViewUnit;
extern "C" {
    pub fn viewUnit_init(this: *mut ViewUnit_t) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn viewUnit_render(this: *const ViewUnit_t);
}
extern "C" {
    pub fn viewUnit_release(this: *mut ViewUnit_t);
}
